package com.example.asn3;

import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;

/**
 * A view that contains a canvas to show the drawing and allow user interaction
 */
public class DiagramView extends Pane implements IModelListener, SMModelListener {
    double width, height;

    /** Abstraction of pen **/
    GraphicsContext gc;

    /** Abstraction of paper **/
    Canvas canvas;

    /** model of the state machine node */
    SMModel model;

    /** Interaction model that handles state machine node selection */
    private InteractionModel iModel;


    /**
     * Constructor method
     */
    public DiagramView() {
        width = 800;
        height = 800;
        canvas = new Canvas(width, height);
        gc = canvas.getGraphicsContext2D();
        gc.setFill(Color.BLACK);
        this.setStyle("-fx-background-color: #b3f7ff;");  // sets background color of the "canvas"
        this.getChildren().add(canvas);
    }

    public void setModel(SMModel newModel) {
        model = newModel;
    }

    /**
     * Method called by the MainUI to attach event handlers to the view components so that the controller can listen in
     * to events generated by the user
     * @param controller calls the model based on user events
     */
    public void setController(AppController controller) {
        canvas.setOnMousePressed(e -> controller.handlePressed(e, e.getX()/width, e.getY()/height));
        canvas.setOnMouseDragged(e -> controller.handleDragged(e, e.getX()/width, e.getY()/height));
        canvas.setOnMouseReleased(e -> controller.handleReleased(e, e.getX()/width, e.getY()/height));
    }

    public void draw() {

    }

    @Override
    public void iModelChanged() {

    }

    @Override
    public void modelChanged() {

    }
}
